### ISSUE TITLE
Easypeasy with "safeAreaLayoutGuide"

### ISSUE THREAD

**Issue by ServusJon** [kylejm/Cut#6]
Hey, saw you use "safeAreaLayoutGuide" with easypeasy. I tried the same and I always get error that identifier is unresolved. I also use the same version of easypeasy like you do. Any hints?

**Comment by ky1ejs** [comment]
Have you checked that you're using it just like this?

https://github.com/kylejm/Cut/blob/c915d124c6eaffead78efce9c33020928aeb5361/Cut/Feed/FeedView.swift#L93

As in, within a UIView and so on?

**Comment by ServusJon** [comment]
Hey,

I tried, but I am getting this error. Do you know what I am doing wrong? I am using easypeasy as a pod from nakiostudio.

Thank you!

**Comment by ky1ejs** [comment]
Not without seeing the code, sorry :/

**Comment by ServusJon** [comment]
Which version of easypeasy do you use?
I get undefined errors when i am trying to use the safelayoutguide :(

**Comment by ky1ejs** [comment]
This is the version used in this project:
https://github.com/kylejm/Cut/blob/master/Cartfile.resolved#L2

**Comment by ServusJon** [comment]
Tried it with your version, but always get the error that safearealayoutguide is undefined :-(
